- hosts: localhost
  connection: local
  tags: all
  pre_tasks:
    - name: Pre-task | Update package cache (Ubuntu)
      become: true
      ansible.builtin.apt:
        update-cache: yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Pre-task | Update package cache (Mac)
      become: false
      community.general.homebrew:
        update_homebrew: yes
      changed_when: false
      when: ansible_distribution == "MacOSX"

- hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Register output of $HOME lookup
      ansible.builtin.debug:
        msg: "{{ lookup('env', 'HOME') }}"
      register: env
    - ansible.builtin.debug:
      var: env

- hosts: localhost
  connection: local
  become: true
  roles:
    - base
