taps:
  - homebrew/cask-fonts

formulae:
  - bat
  - btop
  - fd
  - fzf
  - gawk
  - gnu-sed
  - go
  - imagemagick
  - julia
  - lsd
  - ncdu
  - neofetch
  - neovim
  - node
  - pandoc
  - pstree
  - python
  - ripgrep
  - stow
  - tldr
  - tmux
  - yarn
  - zoxide
  - zsh

casks:
  - arduino
  - gimp
  - google-chrome
  - kitty
  - mactex-no-gui
  - neovide
  - skim
  - font-mononoki-nerd-font
  - font-fira-code-nerd-font
  - font-hack-nerd-font
  - font-agave-nerd-font

dotfiles:
  - bash
  - btop
  - kitty
  - kmonad
  - lazygit
  - nvim
  - readline
  - stylua
  - tmux
  - vim
  - zsh
