sources:
  - ppa:jonathonf/vim
  - ppa:neovim-ppa/stable

packages:
  - bspwm
  - curl
  - git
  - imagemagick
  - make
  - ncdu
  - neovim
  - nitrogen
  - nodejs
  - npm
  # - polybar
  - rofi
  - stow
  - sxhkd
  - vim
  - zsh

dotfiles:
  - bash
  - bspwm
  - btop
  - kitty
  - kmonad
  - lazygit
  - nvim
  - picom
  - polybar
  - readline
  - stylua
  - sxhkd
  - tmux
  - vim
  - zsh
