- name: Clone dotfiles repository
  become: false
  ansible.builtin.git:
    repo: "https://github.com/austinliuigi/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    clone: true

# - name: Stow dotfiles
#   ansible.builtin.shell: |
#     stow -v -t {{ ansible_user_dir }}
#   args:
#     chdir: "{{ ansible_user_dir }}/dotfiles"
#     executable: /bin/bash
