- name: Clone dotfiles repository
  become: false
  ansible.builtin.git:
    repo: "https://github.com/austinliuigi/dotfiles.git"
    dest: "{{ user_dir }}/dotfiles"
    clone: true
  register: clone_dotfiles

# use shell instead of ansible.builtin.shell if on
# version < 2.10.4 (https://github.com/ansible/ansible/issues/72627)
- name: Stow dotfiles
  loop: "{{ dotfiles }}"
  shell:
    cmd: stow -v --target={{ user_dir }} {{ item }}
    chdir: "{{ user_dir }}/dotfiles"
    executable: /bin/bash
  register: output
  changed_when: "'LINK' in output.stderr"
  when: clone_dotfiles.failed == false
