# Add sources
- name: Add sources
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: "present"
  loop: "{{ sources }}"

# Install packages
- name: Install packages
  become: true
  package:
    name: "{{ packages }}"
    state: "present"

- name: Install fonts
  become: true
  copy:
    src: fonts/
    dest: /usr/local/share/fonts/

# - name: Build neovim from source
#   become: true
#   ansible.builtin.shell: |
#     apt install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen
#     git clone https://github.com/neovim/neovim && \
#     cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo && \
#     make install

# - name: Install kitty
#   become: false
#   ansible.builtin.shell: |
#     curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
#     ln -s ~/.local/kitty.app/bin/kitty ~/.local/bin/
#     cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/
#     cp ~/.local/kitty.app/share/applications/kitty-open.desktop ~/.local/share/applications/
#     sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
#     sed -i "s|Exec=kitty|Exec=/home/$USER/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop

# - name: Install kmonad
#   become: true
#   ansible.builtin.shell: |
#     curl -sSL https://get.haskellstack.org/ | sh
#     git clone https://github.com/kmonad/kmonad.git ~/.local/kmonad
#     cd ~/.local/kmonad
#     stack install
